config/routes.rb
Sobiwi::Application.routes.draw do

  root to: 'pages#index'

  resources :message_threads do
    resources :messages
  end

  resource :user, except: [:new, :create, :show] do
    resources :virtual_churches, path: "churches", controller: "users/virtual_churches"
  end
  resources :users, only: [] do
    get 'home'
    get 'profile'
    member do
      post 'follow'
    end
  end

  resources :notes, only: [:new, :create, :destroy]

  resources :virtual_churches, except: [:index], path: "churches" do
    member do
      post 'join'
    end
  end

  get '/login' => 'sessions#new', as: :login
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_handle
  match '/auth/failure', to: 'sessions#failure'
  match '/logout', to: 'sessions#destroy', as: :logout

  resources :identities, only: [:new]
  namespace :identity do
    resources :passwords, only: [:new, :create, :edit, :update]
  end

  get '/about' => redirect("http://i.cs.hku.hk/fyp/2011/fyp11011/public_html")

  scope '/read' do
    get '/:book_code/:chapter' => 'bibles#show_chapter', as: :chapter
    get '/:book_code/:chapter/:verse' => 'bibles#show_verse', as: :verse
  end

  get '/map' => 'pages#map'
  get '/search-user' => 'pages#search_user', as: :search_user
  get '/search-church' => 'pages#search_church', as: :search_church

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :message_thread
  belongs_to :user

  scope :latest, lambda { |n| order("messages.created_at DESC").limit(n) }

  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_logged_in!
  before_filter :get_default_message_thread

  def create
    @message = current_user.messages.build(params[:message])
    @message.message_thread = @message_thread

    @message.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @message = current_user.messages.find(params[:id])
    @message.destroy
    push_flash :success
    redirect_to :back
  end

  private

  def get_default_message_thread
    @message_thread = current_user.message_threads.find params[:message_thread_id]
  end
end

app/views/messages/_message.html.erb
<%- user = UserDecorator.decorate message.user %>
<tr>
  <td style="width: 40px"><%= user.avatar_with_link(:size_40_40) %></td>
  <td>
    <%= simple_format message.content %>
    <p style="font-size: smaller"><%= time_ago_in_words(message.created_at) %></p>
  </td>
  <td style="width: 80px">
    <%- if message.user == current_user %>
    <%= link_to I18n.t("words.delete"), message_thread_message_path(message.message_thread, message), method: :delete, class: "btn btn-danger", id: "delete_message_#{message.id}" %>
    <%- end %>
  </td>
</tr>

app/views/messages/create.js.erb
(function($) {
  $("#message_content").focus();
  $("form.new_message .alert").remove();
})(jQuery);
<%- if @message.valid? %>
  (function($) {
    $("#message_content").val("");
    $message = $("<%= j render(@message) %>").hide();
    $("#messages-table tbody").prepend($message);
    $message.fadeIn();
  })(jQuery);
<%- else %>
  (function($) {
    $notice = $("<div class=\"alert alert-error fade in\"><a class=\"close\" data-dismiss=\"alert\">&times;</a><p><%= @message.errors[:content].join %></p></div>").hide();
    $("#message_content").after($notice);
    $notice.fadeIn();
  })(jQuery);
<%- end %>