config/routes.rb
Sobiwi::Application.routes.draw do

  root to: 'pages#index'

  resources :message_threads do
    resources :messages
  end

  resource :user, except: [:new, :create, :show] do
    resources :virtual_churches, path: "churches", controller: "users/virtual_churches"
  end
  resources :users, only: [] do
    get 'home'
    get 'profile'
    member do
      post 'follow'
    end
  end

  resources :notes, only: [:new, :create, :destroy]

  resources :virtual_churches, except: [:index], path: "churches" do
    member do
      post 'join'
    end
  end

  get '/login' => 'sessions#new', as: :login
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_handle
  match '/auth/failure', to: 'sessions#failure'
  match '/logout', to: 'sessions#destroy', as: :logout

  resources :identities, only: [:new]
  namespace :identity do
    resources :passwords, only: [:new, :create, :edit, :update]
  end

  get '/about' => redirect("http://i.cs.hku.hk/fyp/2011/fyp11011/public_html")

  scope '/read' do
    get '/:book_code/:chapter' => 'bibles#show_chapter', as: :chapter
    get '/:book_code/:chapter/:verse' => 'bibles#show_verse', as: :verse
  end

  get '/map' => 'pages#map'
  get '/search-user' => 'pages#search_user', as: :search_user
  get '/search-church' => 'pages#search_church', as: :search_church

end

app/models/message_thread.rb
class MessageThread < ActiveRecord::Base
  has_many :message_thread_users
  has_many :users, through: :message_thread_users

  has_many :messages

  scope :involving, lambda { |user|
    joins(:message_thread_users).where("message_thread_users.user_id = ?", user.id)
  }

  after_create :generate_uniq_id

  class << self
    def threads_involving(current_user)
      thread_ids = MessageThreadUser.where(user_id: current_user.id).collect(&:message_thread_id)
      where(id: thread_ids)
    end

    def reuse_or_create(current_user, message_thread_params)
      user_ids = ([current_user.id] + message_thread_params[:user_ids]).uniq.delete_if(&:blank?).map(&:to_i)
      message_content = message_thread_params[:messages][:content]

      message_thread = MessageThread.where(uniq_id: user_ids.sort.join("--")).first

      if message_thread.nil?
        message_thread = MessageThread.new

        # create mesasge_thread_users
        user_ids.each do |user_id|
          message_thread.message_thread_users.build(user_id: user_id)
        end
      end

      # create initial message
      unless message_content.blank?
        message_thread.messages.build(user_id: current_user.id, content: message_content)
      end

      message_thread.save!
      message_thread
    end
  end

  private

  def generate_uniq_id
    update_attribute(:uniq_id, message_thread_users.map(&:user_id).sort.join("--"))
  end
end

app/controllers/message_threads_controller.rb
class MessageThreadsController < ApplicationController
  before_filter :require_logged_in!

  layout "membership"

  def index
    @message_threads = MessageThread.threads_involving(current_user)
                                    .delete_if { |message_thread| message_thread.messages.blank? }
                                    .sort_by { |message_thread| message_thread.messages.last.try(:created_at) }
                                    .reverse
  end

  def show
    @message_thread = MessageThread.involving(current_user).find params[:id]
    @users = UserDecorator.decorate @message_thread.users.exclude(current_user)
    @messages = @message_thread.messages.page(params[:page]).per(10)
  end

  def new
    @message_thread = MessageThread.new
    @following_friends = current_user.following_friends
    @friends_following_me = current_user.friends_following_me
  end

  def create
    @message_thread = MessageThread.reuse_or_create(current_user, params[:message_thread])

    redirect_to message_thread_path(@message_thread)
  end
end

app/views/message_threads/index.html.erb
<div class="page-header">
  <h1>
    <%= t("words.messages") %>
    <small><%= link_to t("words.new"), new_message_thread_path, class: "btn btn-primary" %></small>
  </h1>
</div>

<table id="message-threads" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="width: 120px"><%= t("messages.index.titles.users") %></th>
      <th><%= t("messages.index.titles.latest_message") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @message_threads.each do |message_thread| %>
      <%-
        users = UserDecorator.decorate message_thread.users.exclude(current_user)
        users = UserDecorator.decorate [current_user] if users.blank?
        latest_message = message_thread.messages.latest(1).first
        latest_message_user = UserDecorator.decorate latest_message.try(:user)
      %>
      <tr>
        <td style="overflow: hidden">
          <%= users.map { |user| user.avatar_with_link(:size_40_40, {class: "pull-left"}) }.join.html_safe %>
        </td>
        <td style="overflow: hidden">
          <%- if latest_message %>
            <%= latest_message_user.avatar_with_link(:size_40_40, {class: "pull-left"} ) %>
            <blockquote class="pull-left" style="margin-left: 10px">
              <%= simple_format(latest_message.content.truncate(30)) %>
              <p style="font-size: smaller"><%= time_ago_in_words(latest_message.created_at) %></p>
            </blockquote>
          <%- end %>
        </td>
        <td>
          <%= link_to t("words.read"), message_thread_path(message_thread), class: "btn" %>
        </td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/message_threads/new.html.erb
<div class="page-header">
  <h1>
    <%= t("messages.new.title") %>
  </h1>
</div>

<%= simple_form_for @message_thread, html: { class: "form-horizontal new_message" } do |f| %>
  <fieldset>
    <legend>Friends you are following</legend>
    <div class="friends-checker">
      <%= f.association :users, collection: @following_friends, as: :check_boxes, label: I18n.t("messages.index.titles.users"), label_method: lambda { |user|
        user = UserDecorator.new(user)
        user.avatar_with_fake_link(:size_40_40, data: { checking: "message_thread_user_ids_#{user.id}" } )
      } %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Friends who are following you</legend>
    <div class="friends-checker">
      <%= f.association :users, collection: @friends_following_me, as: :check_boxes, label: I18n.t("messages.index.titles.users"), label_method: lambda { |user|
        user = UserDecorator.new(user)
        user.avatar_with_fake_link(:size_40_40, data: { checking: "message_thread_user_ids_#{user.id}" } )
      } %>
    </div>
  </fieldset>
  <%= f.fields_for :messages do |ff| %>
  <%= ff.input :content, label: Message.human_attribute_name(:content) %>
  <%- end %>

  <div class="form-actions">
    <%= f.button :submit, t("words.save"), :class => 'btn-primary' %>
  </div>
<%- end %>

app/views/message_threads/show.html.erb
<div class="page-header">
  <h1>
    <%= t("words.messages") %>
    <small><%= t("messages.index.titles.users") %> <%= @users.map(&:display_name).to_sentence %></small>
  </h1>
</div>

<%= simple_form_for [@message_thread, Message.new], remote: true, html: { class: "form-horizontal new_message" } do |f| %>
  <%= f.input :content, autofocus: true, input_html: { class: "input-xlarge", rows: 3 } %>
  <div class="form-actions">
    <%= f.button :submit, t("words.send"), :class => 'btn-primary' %>
  </div>
<%- end %>

<%- reversed_messages = @messages.reverse %>
<table id="messages-table" class="table table-striped">
  <tbody>
    <%= render reversed_messages %>
  </tbody>
</table>

<%= paginate @messages %>