config/routes.rb
Sobiwi::Application.routes.draw do

  root to: 'pages#index'

  resources :message_threads do
    resources :messages
  end

  resource :user, except: [:new, :create, :show] do
    resources :virtual_churches, path: "churches", controller: "users/virtual_churches"
  end
  resources :users, only: [] do
    get 'home'
    get 'profile'
    member do
      post 'follow'
    end
  end

  resources :notes, only: [:new, :create, :destroy]

  resources :virtual_churches, except: [:index], path: "churches" do
    member do
      post 'join'
    end
  end

  get '/login' => 'sessions#new', as: :login
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_handle
  match '/auth/failure', to: 'sessions#failure'
  match '/logout', to: 'sessions#destroy', as: :logout

  resources :identities, only: [:new]
  namespace :identity do
    resources :passwords, only: [:new, :create, :edit, :update]
  end

  get '/about' => redirect("http://i.cs.hku.hk/fyp/2011/fyp11011/public_html")

  scope '/read' do
    get '/:book_code/:chapter' => 'bibles#show_chapter', as: :chapter
    get '/:book_code/:chapter/:verse' => 'bibles#show_verse', as: :verse
  end

  get '/map' => 'pages#map'
  get '/search-user' => 'pages#search_user', as: :search_user
  get '/search-church' => 'pages#search_church', as: :search_church

end

app/views/shared/_all_books.html.erb
<%- if chosen_bible.present? %>
  <section>
    <h2><%= chosen_bible.name %></h2>
    <div class="row">
      <%- chosen_bible.testaments.each do |testament| %>
        <div class="span2">
          <h3><%= testament.name %></h3>
          <ul class="unstyled">
            <%- testament.books.each do |book| %>
              <li>
                <%= link_to book.name, chapter_path(book.to_chapter_path_hash), rel: "tooltip", title: t(".read", name: t("bibles.formats.verse", book_name: book.name, chapter: 1, verse: 1)) %>
              </li>
            <%- end %>
          </ul>
        </div>
      <%- end %>
    </div>
  </section>
<%- end %>

app/views/shared/_bibles_choser.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(".title") %></a>
<ul class="dropdown-menu">
  <li><%= link_to t(".chosen", name: chosen_bible.name), "?choose_bible=#{chosen_bible.bible_code}"%></li>
  <li class="divider"></li>
  <%- available_bibles.each do |bible| %>
    <li><%= link_to bible.name, "?choose_bible=#{bible.bible_code}"%></li>
  <%- end %>
</ul>

app/views/shared/_footer.html.erb
<footer class="footer" style="background: #333">
  <div class="container">
    <p class="pull-left">
      <%= copyright %> |
      <%= link_to t(".about"), :about, target: "_blank" %>
    </p>
    <p class="pull-right">
      <%= link_to t(".back_to_top"), "#" %>
    </p>
  </div>
</footer>

<%= javascript_include_tag "application" %>

app/views/shared/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
<%= csrf_meta_tags %>
<!-- The below script Makes IE understand the new html5 tags are there and applies our CSS to it -->
<!--[if IE]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<title><%= t("site.name") %></title>

<%= stylesheet_link_tag    "application" %>

app/views/shared/_locales_choser.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(".title") %></a>
<ul class="dropdown-menu">
  <li><%= link_to t(".chosen", name: chosen_locale.name), "?locale=#{chosen_locale.locale_code}" %></li>
  <li class="divider"></li>
  <%- available_locales.each do |locale| %>
    <li><%= link_to locale.name, "?locale=#{locale.locale_code}"%></li>
  <%- end %>
</ul>

app/views/shared/_site_messages.html.erb
<%- if has_flash?(:default) %>
  <div class="row">
    <div class="offset2 span8">
      <%= flush_flash(:default, :using => "shared/site_messages_template") %>
    </div>
  </div>
<%- end %>

app/views/shared/_site_messages_template.html.erb
<%- messages.each do |message| %>
  <%-
    message_type = case message[:message_type]
    when :success
      "alert-success"
    when :failure
      "alert-error"
    when :warning
      ""
    when :info
      "alert-info"
    else
      "alert-error"
    end

    classes = ["alert", message_type, "alert-block", "fade in"].compact.join(" ")
  %>
  <div class="<%= classes %>">
    <a class="close" data-dismiss="alert">&times;</a>
    <p><%= message[:content].html_safe %></p>
  </div>
<%- end %>

app/views/shared/_timeline.html.erb
<section>
  <div class="page-header" style="margin-bottom: 0">
    <h1><small><%= t("timeline.title") %></small></h1>
  </div>

  <%= render partial: notes, as: :note %>
  <%= paginate(notes) %>
</section>

app/views/shared/_topbar.html.erb
<div class="navbar navbar-fixed-top" data-dropdown="dropdown">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <h3><%= link_to t("site.name"), :root, class: "brand" %></h3>
      <div class="nav-collapse">
        <ul class="nav pull-left">
          <li><%= registration_profile_link %></li>
          <%- if logged_in? %>
          <li><%= link_to t("words.messages"), message_threads_path %></li>
          <li><%= link_to t("words.virtual_churches"), user_virtual_churches_path %></li>
          <%- end %>
          <li><%= sign_in_out_link %></li>
        </ul>
        <ul class="nav secondary-nav pull-right">
          <li class="dropdown"><%= render partial: "shared/bibles_choser" %></li>
          <li class="dropdown"><%= render partial: "shared/locales_choser" %></li>
        </ul>
        <%= form_tag search_user_path, method: :get, class: "navbar-form pull-right", id: "search-user-form" do |f| %>
          <%= text_field_tag "search_user_email", params[:search_user_email], class: "search-query span2", placeholder: "Search User by Email" %>
          <%= submit_tag nil, value: "commit", style: "position: absolute; left: -9999px; width: 1px; height: 1px;" %>
        <%- end %>
        <%= form_tag search_church_path, method: :get, class: "navbar-form pull-right", id: "search-church-form" do |f| %>
        <%= text_field_tag "search_church_name", params[:search_church_name], class: "search-query span2", placeholder: "Search Church by Name" %>
          <%= submit_tag nil, value: "commit", style: "position: absolute; left: -9999px; width: 1px; height: 1px;" %>
        <%- end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_profile.html.erb
<%- if defined?(user) %>
  <section>
    <div class="page-header">
      <h1>
        <%= user.display_name %>
        <%= follow_button(user) %>
        <%- if logged_in? && user == current_user %>
        <%= link_to t("words.edit"), edit_user_path, class: "btn btn-mini btn-primary" %>
          <%= link_to t("words.unregister"), user_path, method: :delete, confirm: t("words.confirm_delete"), class: "btn btn-mini btn-danger", id: "destroy_user" %>
        <%- end %>
      </h1>
    </div>

    <div class="rows">
      <h4><%= t(".subtitles.owned_virtual_churches") %></h4>
      <ul>
        <%- if user.owned_virtual_churches.any? %>
          <%- user.owned_virtual_churches.each do |virtual_church| %>
            <li><%= link_to virtual_church.name, virtual_church_path(virtual_church) %></li>
          <%- end %>
        <%- else %>
          <li><%= t("words.not_yet") %></li>
        <%- end %>
      </ul>
    </div>

    <div class="rows">
      <h4><%= t(".subtitles.joined_virtual_churches") %></h4>
      <ul>
        <%- if user.memberships.any? %>
          <%- user.memberships.each do |membership| %>
            <li><%= link_to membership.virtual_church.name, virtual_church_path(membership.virtual_church) %></li>
          <%- end %>
        <%- else %>
          <li><%= t("words.not_yet") %></li>
        <%- end %>
      </ul>
    </div>

    <div class="rows">
      <h4><%= t(".subtitles.following_users") %></h4>
      <ul>
        <%- if user.followships.any? %>
          <%- user.followships.each do |followship| %>
            <li><%= link_to followship.following_user.display_name, user_profile_path(followship.following_user) %></li>
          <%- end %>
        <%- else %>
          <li><%= t("words.not_yet") %></li>
        <%- end%>
      </ul>
    </div>

    <div class="rows">
      <h4><%= t(".subtitles.followed_by_users") %></h4>
      <ul>
        <%- if user.passive_followships.any? %>
          <%- user.passive_followships.each do |followship| %>
            <li><%= link_to followship.user.display_name, user_profile_path(followship.user) %></li>
          <%- end %>
        <%- else %>
          <li><%= t("words.not_yet") %></li>
        <%- end %>
      </ul>
    </div>
  </section>
<%- end %>

app/views/shared/_virtual_church_profile.html.erb
<%- if defined?(virtual_church) %>
  <section>
    <div class="page-header">
      <h1>
        <%= virtual_church.name %>
        <%= join_button(virtual_church) %>
        
        <%- if logged_in? && current_user.owned?(virtual_church) %>
          <%= link_to(t("words.edit"), [:edit, virtual_church], class: "btn small") %>
          <%= link_to t("words.unregister"), virtual_church_path(@virtual_church), method: :delete, confirm: t("words.confirm_delete"), class: "btn danger small" %>
        <%- end %>
      </h1>
    </div>
    
    <div class="rows">
      <div>
        <span class="label normal-label"><%= t(".meta.creator") %></span> <%= link_to virtual_church.creator.display_name, virtual_church.creator %>
      </div>
      <div>
        <span class="label normal-label"><%= t(".meta.description") %></span> <%= simple_format virtual_church.description %>
      </div>
      
      <h2><%= t(".subtitles.users_joined") %></h2>
      <ul>
        <%- if virtual_church.memberships.any? %>
          <%- virtual_church.memberships.each do |membership| %>
            <li><%= link_to membership.user.display_name, user_profile_path(membership.user) %></li>
          <%- end %>
        <%- else %>
          <li><%= t("words.not_yet") %></li>
        <%- end %>
      </ul>
    </div>
  </section>
<%- end %>