config/routes.rb
Sobiwi::Application.routes.draw do

  root to: 'pages#index'

  resources :message_threads do
    resources :messages
  end

  resource :user, except: [:new, :create, :show] do
    resources :virtual_churches, path: "churches", controller: "users/virtual_churches"
  end
  resources :users, only: [] do
    get 'home'
    get 'profile'
    member do
      post 'follow'
    end
  end

  resources :notes, only: [:new, :create, :destroy]

  resources :virtual_churches, except: [:index], path: "churches" do
    member do
      post 'join'
    end
  end

  get '/login' => 'sessions#new', as: :login
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_handle
  match '/auth/failure', to: 'sessions#failure'
  match '/logout', to: 'sessions#destroy', as: :logout

  resources :identities, only: [:new]
  namespace :identity do
    resources :passwords, only: [:new, :create, :edit, :update]
  end

  get '/about' => redirect("http://i.cs.hku.hk/fyp/2011/fyp11011/public_html")

  scope '/read' do
    get '/:book_code/:chapter' => 'bibles#show_chapter', as: :chapter
    get '/:book_code/:chapter/:verse' => 'bibles#show_verse', as: :verse
  end

  get '/map' => 'pages#map'
  get '/search-user' => 'pages#search_user', as: :search_user
  get '/search-church' => 'pages#search_church', as: :search_church

end

app/models/bible.rb
class Bible
  attr_reader :bible_code
  attr_reader :name, :short_name
  attr_reader :testaments
  
  # singleton!
  def initialize(bible_code)
    @bible_code = bible_code.to_sym
  end
  private_class_method :new
  def self.instance_of(bible_code)
    $bible_instances ||= {}
    key = bible_code.to_sym
    return $bible_instances[key] if $bible_instances[key].present?
    
    $bible_instances[key] = new(bible_code)
  end
  # end of singleton
  
  class << self
    def all
      BIBLES.map { |bible_code| instance_of(bible_code) }
    end
    
    def has?(bible_code)
      BIBLES.include?(bible_code.to_s)
    end
  end
  
  def name
    I18n.t("bibles.#{bible_code}.name")
  end
  
  def short_name
    I18n.t("bibles.#{bible_code}.short_name")
  end
  
  def testaments
    [:old, :new].map { |testament_code| Testament.instance_of(bible_code, testament_code) }
  end
end

app/controllers/bibles_controller.rb
class BiblesController < ApplicationController
  def show_chapter
    @book = Book.instance_of(chosen_bible.bible_code, params[:book_code])
    @chapter = params[:chapter].to_i
    @verses = VerseDecorator.decorate Verse.where(bible_code: @book.bible.bible_code, book_code: @book.book_code, chapter: @chapter).order("verses.verse ASC")
    @notes = Note.under(@verses).viewable_by(current_user)
  end

  def show_verse
    @verse = Verse.find_by_bible_code_and_book_code_and_chapter_and_verse(chosen_bible.bible_code, params[:book_code], params[:chapter].to_i, params[:verse].to_i)
    @notes = Note.under(@verse).viewable_by(current_user).order("notes.created_at DESC").page(params[:page])
  end
end

app/views/bibles/show_chapter.html.erb
<%= content_for :footer do %>
  <%= coffee_script_tag do %>
    jQuery(($) ->
      notes = [
        <%- @notes.each do |note| %>
          new Note(
            <%= note.id %>,
            "<%= note.type %>",
            "<%= note.label_color %>",
            [
              <%- note.annotations.each do |annotation| %>
                new Annotation(
                  <%= annotation.id %>,
                  <%= annotation.verse.id %>,
                  <%= annotation.verse.verse %>,
                  <%= annotation.from_atom_index %>,
                  <%= annotation.to_atom_index %>
                ),
              <%- end %>
            ]
          ),
        <%- end %>
      ]

      highlight(notes)
      activateHighlighter()
    )
  <%- end %>
<%- end %>

<section>
  <div class="page-header">
    <h1><%= t(".title", book_name: @book.name, chapter: @chapter, verses_count: @book.verses_in_chapter(@chapter).count).html_safe %></small></h1>
  </div>

  <%= paginate_chapters(@book, @chapter) %>
  <%= link_to t("words.disabled"), "#", onclick: "if (window.highlighterActivated()) { $(this).text('#{t("words.enabled")}'); window.deactivateHighlighter() } else { $(this).text('#{t("words.disabled")}'); window.activateHighlighter() } return false", class: "btn btn-info" %>

  <%=
    content_tag(:ul, class: "unstyled highlightable", data: { bible: @book.bible.bible_code, book: @book.book_code, chapter: @chapter }) do
      @verses.map do |verse|
        content_tag(:li, data: { verse: verse.verse_number, :"max-atom" => verse.atoms.count-1}) do
          concat link_to(verse.name, verse_path(verse.to_verse_path_hash), class: "label verse-label")
          verse.atoms.each do |atom|
            concat content_tag(:span, atom[:atom])
          end
        end
      end.join.html_safe
    end
  %>

  <%= paginate_chapters(@book, @chapter) %>
</section>

<div class="modal fade" id="highlighter-modal" style="display: none">
  <%= simple_form_for Note.new, html: { class: "form-horizontal", style: "margin: 0", multipart: true } do |f| %>
    <div style="margin:0;padding:0;display:inline">
      <input id="modal-model_chosen" name="modal_chosen" type="hidden" value="share" />
      <div class="modal-attrs"></div>
    </div>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3><%= I18n.t("notes-modal.add_note") %></h3>
    </div>
    <div class="modal-body">
      <div class="modal-verse">
        <blockquote>
          Placeholder for the verse content<br>
          <cite style="line-height: 24px"><span class="label notice verse-label">Ver 1:2-3</span></cite>
        </blockquote>
      </div>
      <div class="tabbable">
        <ul class="nav nav-tabs">
          <%# Tab Label here %>
          <li class="active">
            <%= link_to I18n.t("notes-modal.tabs.share"), "#modal-note-share", data: { toggle: "tab", :"modal-chosen" => "share"} %>
          </li>
          <li>
            <%= link_to I18n.t("notes-modal.tabs.note"), "#modal-note-note", data: { toggle: "tab", :"modal-chosen" => "note" } %>
          </li>
          <li>
            <%= link_to I18n.t("notes-modal.tabs.image"), "#modal-note-image", data: { toggle: "tab", :"modal-chosen" => "image" } %>
          </li>
          <li>
            <%= link_to I18n.t("notes-modal.tabs.youtube"), "#modal-note-youtube", data: { toggle: "tab", :"modal-chosen" => "youtube" } %>
          </li>
          <li>
            <%= link_to I18n.t("notes-modal.tabs.map"), "#modal-note-map", data: { toggle: "tab", :"modal-chosen" => "map" } %>
          </li>
        </ul>
        <div class="tab-content">
          <%# Tab Content here%>
          <div class="tab-pane active" id="modal-note-share">
            <%= f.fields_for NoteShare.new do |f| %>
              <%= f.input :content, as: :text, input_html: { id: "note_share-content", name: "note_share[content]", class: "input-xlarge", rows: 5 }, autofocus: true %>
            <%- end %>
          </div>
          <div class="tab-pane" id="modal-note-note">
            <%= f.fields_for NoteNote.new do |f| %>
              <%= f.input :title, input_html: { id: "note_note-title", name: "note_note[title]", class: "input-xlarge" } %>
              <%= f.input :content, as: :text, input_html: { id: "note_note-content", name: "note_note[content]", class: "input-xlarge", rows: 5 } %>
            <%- end %>
          </div>
          <div class="tab-pane" id="modal-note-image">
            <%= f.fields_for NoteImage.new do |f| %>
              <%= f.input :title, input_html: { id: "note_image-title", name: "note_image[title]", class: "input-xlarge" } %>
              <%= f.input :image, input_html: { id: "note_image-image", name: "note_image[image]" }, as: :file %>
            <%- end %>
          </div>
          <div class="tab-pane" id="modal-note-youtube">
            <%= f.fields_for NoteYoutube.new do |f| %>
              <%= f.input :title, input_html: { id: "note_youtube-title", name: "note_youtube[title]", class: "input-xlarge" } %>
              <%= f.input :youtube_url, input_html: { id: "note_youtube-youtube_url", name: "note_youtube[youtube_url]", class: "input-xlarge" } %>
            <%- end %>
          </div>
          <div class="tab-pane" id="modal-note-map">
            <%= f.fields_for NoteMap.new do |f| %>
              <%= f.input :title, input_html: { id: "note_map-title", name: "note_map[title]", class: "input-xlarge" } %>
              <%= embed_map(lat: "note_map-latitude", lng: "note_map-longitude", zoom: "note_map-zoom") %>
              <%= f.input :latitude, as: :hidden, input_html: { id: "note_map-latitude", name: "note_map[latitude]" } %>
              <%= f.input :longitude, as: :hidden, input_html: { id: "note_map-longitude", name: "note_map[longitude]" } %>
              <%= f.input :zoom, as: :hidden, input_html: { id: "note_map-zoom", name: "note_map[zoom]" } %>
            <%- end %>
          </div>
        </div>
      </div>
      <%= f.input :privacy, collection: Privacy.all, include_blank: false, label_method: :name, value_method: :value %>
      <%= f.input :label_color, collection: LabelColor.all, as: :radio_buttons, label_method: :name, value_method: :value %>
    </div>
    <div class="modal-footer">
      <input class="btn btn-primary" name="commit" type="submit" value="<%= I18n.t("words.save") %>" />
      <a href="#" onclick="MODAL.modal('hide'); return false" class="btn"><%= I18n.t("words.cancel") %></a>
    </div>
  <%- end %>
</div>

app/views/bibles/show_verse.html.erb
<section>
  <div class="page-header">
    <h1><%= t(".title", book_name: @verse.book.name, chapter: @verse.chapter, verse: @verse.verse).html_safe %></h1>
  </div>

  <blockquote>
    <%= @verse.content %>
  </blockquote>

  <h3>Notes</h3>

  <%= render partial: @notes, as: :note %>
  <%= paginate(@notes) %>
</section>